- name: Copying configs
  ansible.builtin.copy:
    src: "files/aptutil/aptutil.toml"
    dest: "{{ pi_pxe_server_working_dir }}/aptutil/"
    mode: "0644"

- name: Create cache and meta dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "root"
  loop:
    - "{{ pi_pxe_server_working_dir }}/aptutil/meta/"
    - "{{ pi_pxe_server_working_dir }}/aptutil/cache/"
