- name: Create ssh keypairs
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_ed25519
    type: ed25519
    state: present
  become: false

- name: Create working dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ pi_pxe_server_working_dir }}"
    - "{{ pi_pxe_server_working_dir }}/configs"
    - "{{ pi_pxe_server_working_dir }}/dnsmasq"
    - "{{ pi_pxe_server_working_dir }}/http"
    - "{{ pi_pxe_server_working_dir }}/http/configs"
    - "{{ pi_pxe_server_working_dir }}/tftp"

- name: Copy in docker configs
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ pi_pxe_server_working_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - "dnsmasq/Dockerfile"
    - "http/Dockerfile"
    - "docker-compose.yaml"

- name: Set up netboot
  ansible.builtin.include_tasks: netboot.yaml

- name: Check iPXE UEFI binary
  ansible.builtin.stat:
    path: "{{ pi_pxe_server_working_dir }}/tftp/ipxe.efi"
  register: ipxe_efi_stat

- name: Download iPXE UEFI binary
  ansible.builtin.get_url:
    url: "http://boot.ipxe.org/ipxe.efi"
    dest: "{{ pi_pxe_server_working_dir }}/tftp/ipxe.efi"
    mode: "0644"
  when: not ipxe_efi_stat.stat.exists

- name: Check iPXE BIOS binary
  ansible.builtin.stat:
    path: "{{ pi_pxe_server_working_dir }}/tftp/undionly.kpxe"
  register: ipxe_bios_stat

- name: Download iPXE BIOS binary
  ansible.builtin.get_url:
    url: "http://boot.ipxe.org/undionly.kpxe"
    dest: "{{ pi_pxe_server_working_dir }}/tftp/undionly.kpxe"
    mode: "0644"
  when: not ipxe_bios_stat.stat.exists

- name: Template Dnsmasq config
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: "{{ pi_pxe_server_working_dir }}/configs/dnsmasq.conf"
    mode: "0644"

- name: Install fallback autoexec.ipxe in HTTP and TFTP roots
  ansible.builtin.template:
    src: autoexec.ipxe.j2
    dest: "{{ item }}"
    mode: "0644"
  loop:
    - "{{ pi_pxe_server_working_dir }}/http/autoexec.ipxe"
    - "{{ pi_pxe_server_working_dir }}/tftp/autoexec.ipxe"

- name: Print MAC address of each host in the cluster
  ansible.builtin.debug:
    msg: "MAC address of {{ item }} is {{ hostvars[item]['mac'] }}"
  loop: "{{ groups['cluster'] }}"
  when: hostvars[item]['mac'] is defined

- name: Generate preseed for each machine
  ansible.builtin.template:
    src: preseed.cfg.j2
    dest: "{{ pi_pxe_server_working_dir }}/http/configs/{{ hostvars[item]['mac'] | lower }}.cfg"
    mode: "0644"
  loop: "{{ groups['cluster'] }}"

- name: Install docker sdk python
  ansible.builtin.apt:
    name: python3-docker
    state: present

- name: Install docker compose sdk
  ansible.builtin.apt:
    name: docker-compose
    state: present

- name: Set up apt cache
  ansible.builtin.include_tasks: aptutil.yaml

- name: Copy Debian kernel and initrd to HTTP root for iPXE
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    remote_src: true
  loop:
    - {
        src: "{{ pi_pxe_server_working_dir }}/debian-installer/amd64/linux",
        dest: "{{ pi_pxe_server_working_dir }}/http/linux",
      }
    - {
        src: "{{ pi_pxe_server_working_dir }}/debian-installer/amd64/initrd.gz",
        dest: "{{ pi_pxe_server_working_dir }}/http/initrd.gz",
      }

- name: Start PXE server
  community.docker.docker_compose_v2:
    project_src: "{{ pi_pxe_server_working_dir }}"
    state: present
    build: policy
    recreate: "auto"
