
- name: Install base packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - rdma-core
    - opensm
    - ibutils
    - infiniband-diags

- name: Set up interface
  ansible.builtin.template:
  
