- name: Install docker for pxe server
  hosts: pi0
  become: true
  gather_facts: true
  vars:
    docker_install_compose: true
  roles:
    - geerlingguy.docker

- name: Start pxe server
  hosts: pi0
  become: true
  gather_facts: true
  vars:
    # Enable ProxyDHCP so we coexist with the router's DHCP
    pi_pxe_server_proxy_dhcp: true
    pi_pxe_next_server_ip: "{{ ansible_default_ipv4.address }}"
    pi_pxe_listen_interface: "{{ ansible_default_ipv4.interface }}"
  roles:
    - pi_pxe_server

- name: Provision Machines
  hosts: pi0
  gather_facts: true
  tasks:
    - name: Send wake packets
      community.general.wakeonlan:
        mac: "{{ hostvars[item]['mac'] }}"
      delegate_to: pi0
      loop: "{{ groups['cluster'] }}"

    - name: Wait for a bit for them to start up
      ansible.builtin.wait_for_connection:
        timeout: 300
