services:
  dnsmasq:
    build: ./dnsmasq
    volumes:
      - ./configs/dnsmasq.conf:/etc/dnsmasq.conf
      - ./debian-installer/amd64//initrd.gz:/tftp/initrd.gz
      - ./debian-installer/amd64/linux:/tftp/linux
      - ./debian-installer:/tftp/debian-installer/
      - ./debian-installer/amd64/grubx64.efi:/tftp/grubx64.efi
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  http:
    build: ./http
    network_mode: host
    volumes:
      - ./configs/:/usr/share/nginx/html/configs
    environment:
      NGINX_PORT: 80
    restart: unless-stopped
    
  aptutil:
    image: ghcr.io/jlevere/aptutil:latest-arm64
    container_name: aptutil
    ports:
      - "3142:3142"
    volumes:
      - ./aptutil/aptutil.toml:/etc/go-apt-cacher.toml
      - ./aptutil/meta:/meta
      - ./aptutil/cache:/cache
    restart: unless-stopped
    network_mode: host
