
- name: Install proxmox
  hosts: cluster
  become: true
  roles:
    - install_proxmox

# - name: Make ssh keys
#   hosts: localhost
#   tasks:
#     - name: Create cluster sshkey
#       community.crypto.openssh_keypair:
#         path: "{{ playbook_dir }}/keys/internal_cluster_key"
#         type: ed25519
#         state: present

# - name: Move sshkey into cluster
#   hosts: cluster
#   become: true
#   tasks:
#     - name: Copy in key
#       ansible.builtin.copy:
#         src: ./keys/internal_cluster_key
#         dest: "/home/{{ hostvars[item]['ansible_user'] }}/.ssh/id_rsa"
#         mode: "0600"
#       loop: "{{ groups['cluster'] }}"

#     - name: Authorzied keys
#       ansible.posix.authorized_key:
#         user: "{{ hostvars[item]['ansible_user'] }}"
#         state: present
#         key: ./keys/internal_cluster_key.pub
#       loop: "{{ groups['cluster'] }}"


# - name: Install automation tools
#   hosts: cluster
#   become: true
#   tasks:
#     - name: Install python requiremnts
#       ansible.builtin.pip:
#         name: "{{ item }}"
#       loop:
#         - requests
#         - openssh_wrapper
#         - proxmoxer

# - name: Configure proxmox cluster
#   hosts: cluster
#   become: true
#   gather_facts: False
#   roles:
#     - config_proxmox_cluster

