- name: Check cluster status
  ansible.builtin.shell: pvecm status | grep -e "^Node ID"
  register: cluster_status
  ignore_errors: true
  changed_when: False
  when: inventory_hostname != 'machine0'

- name: Debug cluster status
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} cluster status: {{ cluster_status.stdout }}"
  when: inventory_hostname != 'machine0'

- name: Create cluster on the initial node
  ansible.builtin.command:
    cmd: "pvecm create {{ config_proxmox_cluster_name }}"
  when: inventory_hostname == 'machine0' and cluster_status.rc == 1

- name: Add node to cluster
  ansible.builtin.command:
    cmd: "pvecm add {{ groups['cluster']['machine0']['ansible_host'] }}"
  when: inventory_hostname != 'machine0' and cluster_status.rc == 0
