- name: Check if node is already in a cluster
  ansible.builtin.shell: pvecm status | grep -E "^Cluster information|^Node ID"
  register: cluster_status
  ignore_errors: true
  changed_when: false

- name: Determine bootstrap node
  ansible.builtin.set_fact:
    proxmox_bootstrap: "{{ (ansible_play_hosts_all | first) }}"

- name: Create cluster on the bootstrap node
  ansible.builtin.command:
    cmd: "pvecm create {{ config_proxmox_cluster_name }}"
  when: inventory_hostname == proxmox_bootstrap and cluster_status.rc != 0

- name: Add node to cluster
  ansible.builtin.command:
    cmd: "pvecm add {{ hostvars[proxmox_bootstrap].ansible_host }}"
  when: inventory_hostname != proxmox_bootstrap and cluster_status.rc == 0
