---
- name: Ensure cluster hostnames resolve in /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "(^|\\s){{ item }}$"
    state: present
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    backup: true
  loop: "{{ groups['cluster'] }}"
  when: hostvars[item].ansible_host is defined
  tags: [hosts]

- name: Install Proxmox
  ansible.builtin.include_tasks: install_proxmox.yml
  tags: [proxmox]

- name: Distribute ssh keys
  ansible.builtin.include_tasks: ssh_setup.yml
  tags: [ssh]

- name: Create/join Proxmox cluster
  ansible.builtin.include_tasks: cluster_create.yml
  tags: [cluster]
