- name: Copy private key to cluster nodes
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/keys/cluster_key"
    dest: "/root/.ssh/cluster_key"
    mode: "0600"
  delegate_to: "{{ item }}"
  with_items: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"
  become: true

- name: Copy private key to cluster nodes
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/keys/cluster_key"
    dest: "/home/{{ansible_user}}/.ssh/cluster_key"
    mode: "0600"
  delegate_to: "{{ item }}"
  with_items: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"
  become: false
  tags:
    - copy-id

- name: Slurp pub key
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/keys/cluster_key.pub"
  register: ssh_public_key
  delegate_to: localhost
  become: false

- name: Authorized keys debian
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ ssh_public_key.content | b64decode }}"
    state: present
  delegate_to: "{{ item }}"
  with_items: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"
  become: false

- name: Authorized keys root
  ansible.posix.authorized_key:
    user: "root"
    key: "{{ ssh_public_key.content | b64decode }}"
    state: present
  delegate_to: "{{ item }}"
  with_items: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"
  become: true

- name: Clear known_hosts file
  ansible.builtin.file:
    path: ~/.ssh/known_hosts
    state: absent
  become: false

- name: Recreate known_hosts file
  ansible.builtin.file:
    path: ~/.ssh/known_hosts
    state: touch
    mode: '0644'
  become: false

- name: Keyscan known_hosts
  ansible.builtin.shell: "ssh-keyscan -t ed25519 -H {{ hostvars[item].ansible_host }} >> ~/.ssh/known_hosts"
  loop: "{{ groups['cluster'] }}"
  when: hostvars[item].ansible_host is defined
  become: false
