services:
  dnsmasq:
    build: ./dnsmasq
    volumes:
      - ./configs/dnsmasq.conf:/etc/dnsmasq.conf
      - ./tftp:/tftp
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  http:
    build: ./http
    network_mode: host
    volumes:
      - ./http/:/usr/share/nginx/html/
    environment:
      NGINX_PORT: 80
    restart: unless-stopped
