# Override specific values for this environment
image:
  tag: "latest"

# Environment variables configuration - both regular and from secrets
env:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  # Secret values - we'll reference the secret directly
  API_TOKEN:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: API_TOKEN
  VLAN:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: VLAN
  MAC_ADDRESS:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: MAC_ADDRESS
  IP_ADDRESS:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: IP_ADDRESS
  NSEID:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: NSEID
  LASTNAME:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: LASTNAME
  ROOMNUMBER:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: ROOMNUMBER
  PROPERTYID:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: PROPERTYID
  REGMETHODID:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: REGMETHODID
  RATEPLANID:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: RATEPLANID
  PIN:
    valueFrom:
      secretKeyRef:
        name: skyadmin-agent-secrets
        key: PIN

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Additional Helm chart values to ensure proper configuration
serviceAccount:
  create: true
  automount: true

securityContext: {}

podSecurityContext: {}
