# Override specific values for this environment
image:
  tag: "latest"

# Environment variables configuration
env:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"

# Secret environment variables - these will be loaded from the sealed secret
envFrom:
  - secretRef:
      name: skyadmin-agent-secrets

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Additional Helm chart values to ensure proper configuration
serviceAccount:
  create: true
  automount: true

securityContext: {}

podSecurityContext: {}
