pi_pxe_server_tar: "https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/netboot.tar.gz"
pi_pxe_server_tar_checksum: "sha256:3429fa77a3823da5bfb9235a956d8b89b181999f2e23a6a4194c4379630106de"
pi_pxe_server_working_dir: "/opt/pxe"
