- name: Check cluster status
  ansible.builtin.shell: pvecm status | grep -e "^Node ID"
  register: cluster_status
  ignore_errors: true
  changed_when: False
  when: inventory_hostname != 'machine0'

- debug:
    msg: "{{inventory_hostname}} {{cluster_status}}"

- name: Create cluster
  ansible.builtin.command: "pvecm create {{ config_proxmox_cluster_name }}"
  when: cluster_status is defined and cluster_status.rc != 1 and inventory_hostname == 'machine0'

- name: Add self to cluster
  ansible.builtin.command:
    cmd: "pvecm add {{ groups['cluster']['machine0']['ansible_host'] }}"
  when: inventory_hostname != 'machine0'
