- name: Update /etc/hosts file
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1\\s+{{ inventory_hostname }}(\\s|$)"
    state: present
    line: "{{ hostvars[inventory_hostname]['ansible_host'] }} {{ inventory_hostname }}"

- name: Install Proxmox
  ansible.builtin.include_tasks: install_proxmox.yml

- name: Distribute ssh keys
  ansible.builtin.include_tasks: ssh_setup.yml
