- name: Create keypair locally
  community.crypto.openssh_keypair:
    path: "{{ playbook_dir }}/keys/internal_cluster_key"
    type: ed25519
    state: present
  delegate_to: localhost

- name: Copy private key to cluster nodes
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/keys/internal_cluster_key"
    dest: "/root/.ssh/internal_cluster_key" # Adjust path as needed
    mode: "0600" # Ensure only root can read/write
  delegate_to: "{{ item }}"
  with_items: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"
  become: true

- name: Copy private key to cluster nodes
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/keys/internal_cluster_key"
    dest: "/home/{{anible_user}}/.ssh/internal_cluster_key" # Adjust path as needed
    mode: "0600" # Ensure only root can read/write
  delegate_to: "{{ item }}"
  with_items: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"

- name: Slurp pub key
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/keys/internal_cluster_key.pub"
  register: ssh_public_key
  delegate_to: localhost
  become: false

- name: Authorized keys debian
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ ssh_public_key.content | b64decode }}"
    state: present
  delegate_to: "{{ item }}"
  with_items: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"
  become: false

- name: Authorized keys root
  ansible.posix.authorized_key:
    user: "root"
    key: "{{ ssh_public_key.content | b64decode }}"
    state: present
  delegate_to: "{{ item }}"
  with_items: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"
  become: true

- name: Clear known_hosts file
  ansible.builtin.lineinfile:
    path: ~/.ssh/known_hosts
    state: absent
  become: false

- name: Keyscan known_hosts
  ansible.builtin.command:
    cmd: "ssh-keyscan  -t ed25519 -H {{ item }} >> ~/.ssh/known_hosts"
  with_items: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"
  become: false
