apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.16.1
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
          - ip: 192.168.88.20 # K3s node IP
          - ip: 127.0.0.1 # localhost
          - ip: 10.43.0.1 # Kubernetes service network (if needed)
        # No DNS entries since no DNS server exists
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        # ECK automatically enables security and manages Fleet integration
        # Removed reserved settings: xpack.security.enabled, xpack.security.enrollment.enabled
        # Removed Fleet settings as they're managed by ECK when Fleet Server is deployed
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 2Gi
                  cpu: 1
                requests:
                  memory: 1Gi
                  cpu: 0.5
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: local-path # Using local-path for homelab
