apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.16.1
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        # Enable security for Fleet Server integration
        xpack.security.enabled: true
        xpack.security.enrollment.enabled: true
        # Fleet Server requires these settings
        xpack.fleet.agents.enabled: true
        xpack.fleet.packages.enabled: true
        xpack.fleet.templates.enabled: true
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 2Gi
                  cpu: 1
                requests:
                  memory: 1Gi
                  cpu: 0.5
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: local-path # Using local-path for homelab
