apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.16.1
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    # Enable Fleet and Integrations
    xpack.fleet.agents.enabled: true
    xpack.fleet.packages.enabled: true
    xpack.fleet.templates.enabled: true
    # Fleet Server hosts will be configured manually in Kibana UI after deployment
    # since external Windows machines need to use the LoadBalancer IP, not internal DNS
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            limits:
              memory: 1Gi
              cpu: 1
            requests:
              memory: 512Mi
              cpu: 0.5
  http:
    service:
      spec:
        type: ClusterIP
    # tls:
    #   selfSignedCertificate:
    #     disabled: true  # Disable TLS for simplicity
